name: build

on:
  push:
    branches:
      - master

env:
  PROJECT_ID: YOUR_PROJECT_ID # TODO: update Google Cloud project id
  GAR_LOCATION: YOUR_GAR_LOCATION # TODO: update Artifact Registry location
  SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  REGION: YOUR_SERVICE_REGION # TODO: update Cloud Run service region
  DOCKER_USER: ldsoftware

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Ivy Cache
        uses: actions/cache@v1
        with:
          path: ~/.ivy2/cache
          key: ${{runner.os}}-sbt-${{hashFiles('**/build.sbt')}}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: ${{runner.os}}-sbt-${{hashFiles('**/build.sbt')}}
      - name: Coursier cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}
          restore-keys: |
            ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-${{ hashFiles('**/*.sbt') }}-
            ${{ runner.os }}-coursier-cache-${{ matrix.scala }}-
            ${{ runner.os }}-coursier-cache-
      - name: Initialize sbt
        run: sbt clean
      - name: Build
        run: sbt compile
      - name: Unit tests
        run: sbt test

  package:
    name: Build and push Docker image
    needs: build
    if: "!contains(github.event.head_commit.message, 'ci-skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login on docker registry
        run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u ${{ env.DOCKER_USER }} --password-stdin
      - name: Setup git username
        run: git config user.name LukeDS-it
      - name: Setup git email
        run: git config user.email ${{secrets.EMAIL}}
      - name: Release
        run: sbt release
        env:
          DOCKER_USERNAME: ${{ env.DOCKER_USER }}

  deploy:
    name: Deploy on production environment
    needs: package
    runs-on: ubuntu-latest
    environment: manual-actions
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: ${{ env.DOCKER_USER }}/gcp-integration:1.0.0-SNAPSHOT
      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
